//go:build !ignore_autogenerated

// Copyright (c) 2024 Red Hat, Inc.

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OdhNIMAccount) DeepCopyInto(out *OdhNIMAccount) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OdhNIMAccount.
func (in *OdhNIMAccount) DeepCopy() *OdhNIMAccount {
	if in == nil {
		return nil
	}
	out := new(OdhNIMAccount)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OdhNIMAccount) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OdhNIMAccountList) DeepCopyInto(out *OdhNIMAccountList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OdhNIMAccount, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OdhNIMAccountList.
func (in *OdhNIMAccountList) DeepCopy() *OdhNIMAccountList {
	if in == nil {
		return nil
	}
	out := new(OdhNIMAccountList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OdhNIMAccountList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OdhNIMAccountSpec) DeepCopyInto(out *OdhNIMAccountSpec) {
	*out = *in
	out.SecretRef = in.SecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OdhNIMAccountSpec.
func (in *OdhNIMAccountSpec) DeepCopy() *OdhNIMAccountSpec {
	if in == nil {
		return nil
	}
	out := new(OdhNIMAccountSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OdhNIMAccountStatus) DeepCopyInto(out *OdhNIMAccountStatus) {
	*out = *in
	if in.TemplateRef != nil {
		in, out := &in.TemplateRef, &out.TemplateRef
		*out = new(v1.ObjectReference)
		**out = **in
	}
	if in.ConfigMapRef != nil {
		in, out := &in.ConfigMapRef, &out.ConfigMapRef
		*out = new(v1.ObjectReference)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OdhNIMAccountStatus.
func (in *OdhNIMAccountStatus) DeepCopy() *OdhNIMAccountStatus {
	if in == nil {
		return nil
	}
	out := new(OdhNIMAccountStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OdhNIMRuntime) DeepCopyInto(out *OdhNIMRuntime) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OdhNIMRuntime.
func (in *OdhNIMRuntime) DeepCopy() *OdhNIMRuntime {
	if in == nil {
		return nil
	}
	out := new(OdhNIMRuntime)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OdhNIMRuntime) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OdhNIMRuntimeList) DeepCopyInto(out *OdhNIMRuntimeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OdhNIMRuntime, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OdhNIMRuntimeList.
func (in *OdhNIMRuntimeList) DeepCopy() *OdhNIMRuntimeList {
	if in == nil {
		return nil
	}
	out := new(OdhNIMRuntimeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OdhNIMRuntimeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OdhNIMRuntimeSpec) DeepCopyInto(out *OdhNIMRuntimeSpec) {
	*out = *in
	in.InferenceServiceSpec.DeepCopyInto(&out.InferenceServiceSpec)
	in.PvcSpec.DeepCopyInto(&out.PvcSpec)
	out.OdhNIMAccountRef = in.OdhNIMAccountRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OdhNIMRuntimeSpec.
func (in *OdhNIMRuntimeSpec) DeepCopy() *OdhNIMRuntimeSpec {
	if in == nil {
		return nil
	}
	out := new(OdhNIMRuntimeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OdhNIMRuntimeStatus) DeepCopyInto(out *OdhNIMRuntimeStatus) {
	*out = *in
	out.PvcRef = in.PvcRef
	out.ImagePullSecretRef = in.ImagePullSecretRef
	out.NimSecretRef = in.NimSecretRef
	out.ServingRuntimeRef = in.ServingRuntimeRef
	out.InferenceServiceRef = in.InferenceServiceRef
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OdhNIMRuntimeStatus.
func (in *OdhNIMRuntimeStatus) DeepCopy() *OdhNIMRuntimeStatus {
	if in == nil {
		return nil
	}
	out := new(OdhNIMRuntimeStatus)
	in.DeepCopyInto(out)
	return out
}
