//go:build !ignore_autogenerated

// Copyright (c) 2024 Red Hat, Inc.

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OdhNIMRuntime) DeepCopyInto(out *OdhNIMRuntime) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OdhNIMRuntime.
func (in *OdhNIMRuntime) DeepCopy() *OdhNIMRuntime {
	if in == nil {
		return nil
	}
	out := new(OdhNIMRuntime)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OdhNIMRuntime) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OdhNIMRuntimeList) DeepCopyInto(out *OdhNIMRuntimeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OdhNIMRuntime, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OdhNIMRuntimeList.
func (in *OdhNIMRuntimeList) DeepCopy() *OdhNIMRuntimeList {
	if in == nil {
		return nil
	}
	out := new(OdhNIMRuntimeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OdhNIMRuntimeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OdhNIMRuntimeSpec) DeepCopyInto(out *OdhNIMRuntimeSpec) {
	*out = *in
	in.InferenceServiceSpec.DeepCopyInto(&out.InferenceServiceSpec)
	in.PvcSpec.DeepCopyInto(&out.PvcSpec)
	out.OdhNIMAccountRef = in.OdhNIMAccountRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OdhNIMRuntimeSpec.
func (in *OdhNIMRuntimeSpec) DeepCopy() *OdhNIMRuntimeSpec {
	if in == nil {
		return nil
	}
	out := new(OdhNIMRuntimeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OdhNIMRuntimeStatus) DeepCopyInto(out *OdhNIMRuntimeStatus) {
	*out = *in
	out.PvcRef = in.PvcRef
	out.ImagePullSecretRef = in.ImagePullSecretRef
	out.NimSecretRef = in.NimSecretRef
	out.ServingRuntimeRef = in.ServingRuntimeRef
	out.InferenceServiceRef = in.InferenceServiceRef
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OdhNIMRuntimeStatus.
func (in *OdhNIMRuntimeStatus) DeepCopy() *OdhNIMRuntimeStatus {
	if in == nil {
		return nil
	}
	out := new(OdhNIMRuntimeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OdhNimApp) DeepCopyInto(out *OdhNimApp) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OdhNimApp.
func (in *OdhNimApp) DeepCopy() *OdhNimApp {
	if in == nil {
		return nil
	}
	out := new(OdhNimApp)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OdhNimApp) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OdhNimAppList) DeepCopyInto(out *OdhNimAppList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OdhNimApp, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OdhNimAppList.
func (in *OdhNimAppList) DeepCopy() *OdhNimAppList {
	if in == nil {
		return nil
	}
	out := new(OdhNimAppList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OdhNimAppList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OdhNimAppSpec) DeepCopyInto(out *OdhNimAppSpec) {
	*out = *in
	in.ApiKey.DeepCopyInto(&out.ApiKey)
	in.Content.DeepCopyInto(&out.Content)
	if in.TemplateRef != nil {
		in, out := &in.TemplateRef, &out.TemplateRef
		*out = new(corev1.ObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OdhNimAppSpec.
func (in *OdhNimAppSpec) DeepCopy() *OdhNimAppSpec {
	if in == nil {
		return nil
	}
	out := new(OdhNimAppSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OdhNimAppSpecApiKey) DeepCopyInto(out *OdhNimAppSpecApiKey) {
	*out = *in
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(corev1.ObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OdhNimAppSpecApiKey.
func (in *OdhNimAppSpecApiKey) DeepCopy() *OdhNimAppSpecApiKey {
	if in == nil {
		return nil
	}
	out := new(OdhNimAppSpecApiKey)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OdhNimAppSpecContent) DeepCopyInto(out *OdhNimAppSpecContent) {
	*out = *in
	if in.ConfigMapRef != nil {
		in, out := &in.ConfigMapRef, &out.ConfigMapRef
		*out = new(corev1.ObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OdhNimAppSpecContent.
func (in *OdhNimAppSpecContent) DeepCopy() *OdhNimAppSpecContent {
	if in == nil {
		return nil
	}
	out := new(OdhNimAppSpecContent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OdhNimAppStatus) DeepCopyInto(out *OdhNimAppStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OdhNimAppStatus.
func (in *OdhNimAppStatus) DeepCopy() *OdhNimAppStatus {
	if in == nil {
		return nil
	}
	out := new(OdhNimAppStatus)
	in.DeepCopyInto(out)
	return out
}
